### ISSUE TITLE
[BUG]Documentation

### ISSUE THREAD

**Issue by mclancy10006** [emalderson/ThePhish#4] opened 2021-10-15 20:29 UTC
you need to have a Case Template created in TheHive named 'ThePhish' or you get an error.  When my only Case Template was named reported-email I kept getting errors and it would not kick off Analysis.

**Comment by mgrant0** [comment] 2021-10-16 14:53
Any suggestions on how to proceed?

**Comment by emalderson** [comment] 2021-10-16 15:47
As I said earlier, ThePhish automatically creates a case template named "ThePhish" if it does not exist yet. Check if the problem is on your side, maybe due to your configuration or work environment. Don't forget to specify your work environment following this [Issue Template](https://github.com/emalderson/ThePhish/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when opening issues related to possible bugs.

**Comment by emalderson** [comment] 2021-11-01 17:12
This problem has been fixed in the documentation, closed.

**Closed by emalderson** 2021-11-01 17:12 UTC
Labels: bug
